### ISSUE TITLE
Expired Entries do not Delete from html cache

### ISSUE THREAD

**Issue by jmcgaha** [putyourlightson/craft-blitz#101]
I'm following up on Issue #69 as I work with the developer that filed that issue.

On our staging server we have updated to the latest Blitz 2.0.8 and Craft 3.1.23.
If I make a new entry and set an expiration date for a few minutes in the future, I then load the page and make sure that Blitz saved an html cached version.

After the expiration date has passed I either click the control panel "Refresh Expired Cache" button or I run the ./craft blitz/cache/refresh-expired command.

What happens next are the respective records are removed from the database, but the html files are never removed.

Let me know if you need any more information from me.

**Comment by putyourlightson** [comment]
Since that previous issue was a long thread and seems to have not been properly resolved, I would suggest you send credentials (CP & FTP) to info@putyourlightson.net and I can take a look. I'm not sure how to best address this otherwise as this is not something I can reproduce and may be server specific.
