### ISSUE TITLE
What happens when I use craft cache tags along with blitz?

### ISSUE THREAD

**Issue by piotrpog** [putyourlightson/craft-blitz#107]
My website has search and filtering functionality based on URL queries so i cannot use blitz everywhere.

I also have multiple `{% cache %}` tags that help me with rendering complicated navigation. If I disable these tags, parts of my page not cached with blitz will have poor performance.

What will happen if i use both blitz and `{% cache %}` tags? Can i make both these things work together without any problems?

**Comment by putyourlightson** [comment]
> If I disable these tags, parts of my page not cached with blitz will have poor performance.

Blitz caches full pages, so there is no case where parts of your page are not cached. There is the dynamic content tag of course, but even the output from the tag is cached and the JS code makes that part of the page dynamic.

If the issue is that you want to use `{% cache %}` tags in pages that are _not_ cached by Blitz then that is fine. The problem is when you use `{% cache %}` tags in pages that _are_ cached by Blitz, as then there is the possibility that Blitz will not be able to detect which elements are output on the page (since they may have already been cached by the `{% cache %}` tags) and therefore Blitz cache invalidation will not work as expected. Does that make sense?
