### ISSUE TITLE
[Question] Critical CSS

### ISSUE THREAD

**Issue by umkasanki** [putyourlightson/craft-blitz#119]
Hello.
Is there a way to use critical CSS with blitz?
I use cookie-based checking for CSS loading.
```
{% set criticalVersion = getCookie( 'critical-css-version' ) %}
{% set cssPath = rev('css/site.combined.css') %}

{% if criticalVersion == cssPath %}
    <link rel="stylesheet" href="{{ cssPath }}">
{% else %}
    {% do 'critical-css-version' | setCookie(cssPath, now | date_modify("+7 days").timestamp) %}
    {% block _inline_css %}
    {% endblock %}
    <script>
        {{ source("_inlinejs/cssrelpreload.min.js") }}
    </script>
    <link rel="preload" href="{{ cssPath }}" as="style" onload="this.onload=null;this.rel='stylesheet'">
    <noscript>
        <link rel="stylesheet" href="{{ cssPath }}">
    </noscript>
{% endif %}
```

I tried load CSS through ```{{ craft.blitz.getUri('/template/name') }}``` , but its not working good for inject styles in head. Until the end of the ajax request, the page is displayed without styles.

Thank you for great plugin!

**Comment by putyourlightson** [comment]
This is not really going to work since it sounds like you're trying to make the page dynamic using cookies in twig. One workaround would be to load the critical CSS using pure Javascript, rather than using the AJAX approach. However, since the page is being fully cached, why not load the critical CSS on every request? I can't think of any downside to doing so.

**Comment by umkasanki** [comment]
Okay, got it
