### ISSUE TITLE
Can craft.blitz.getUri('/template/name') support hidden templates?

### ISSUE THREAD

**Issue by BenParizek** [putyourlightson/craft-blitz#129]
This is a FR for this `getUri` tag or for another similar tag.

Right now, you can use the following to load templates that are publicly accessible:

```
{{ craft.blitz.getUri('/template/name') }}
```

However, if you have a template partial that really doesn't need it's own URL the `getUri` tag will not load a hidden template (just returns blank):

```
{{ craft.blitz.getUri('_partials/name') }}
```

It appears the getUri tag adds a `nocache` parameter that may matter for public URLs, but it also appears the tag relies on sending a get request to render the HTML and insert it on the page via JS.

It may be nice to have an option that just rendered the template given using the underlying `renderTemplate` method directly, and not require a page request and publicly accessible template.

**Comment by putyourlightson** [comment]
As you correctly observed, Blitz relies on Javascript to dynamically inject content. If we added a tag to render a hidden template then that would make _every_ hidden template available using a public controller action which would be a security concern. My suggestion would be to have a template folder specifically for dynamic AJAX requests, for example:

    {{ craft.blitz.getUri('/ajax/name') }}

**Comment by BenParizek** [comment]
@putyourlightson I see. Definitely not something to consider as a feature for this tag.

Would you consider a separate tag that only took the template name provided in the template and didn't open up the door to any public variables? Something like:

```
{{ craft.blitz.renderTemplate('_includes/name', params) }}
```

I can definitely work around this request with the dedicated folder direction you mention above, it just feels semantically incorrect to me, as the whole point of having hidden template folders is to avoid having URLs that can 404 that shouldn't be accessed directly at all.

**Comment by putyourlightson** [comment]
Such a tag would require Blitz to parse the statically cached page before returning it, which is going to slow things down significantly, defeating the purpose of a lot of what Blitz is trying to do. It also will not work when server rewrites are set up as in that case the cached HTML file is returned directly by the server and not by Blitz. 

To your point about semantics, I think that hidden template files and folders are intended for Twig inclusion and extension rather than direct access, but I understand where you're coming from. If you're concerned about templates intended for AJAX requests being accessed directly then you could add the following tag to the top of your template.

```
{% if not craft.app.request.isAjax %}
    {% exit 404 %}
{% endif %}
```

**Comment by putyourlightson** [comment]
After our chat I found a way to make this work and added in https://github.com/putyourlightson/craft-blitz/commit/e074aa479a66a1754c1f291765742b1f1f3b007f, thanks Ben!
