### ISSUE TITLE
Refreshing Blitz Cache fails

### ISSUE THREAD

**Issue by hiasl** [putyourlightson/craft-blitz#137]
Our db table queue contains hundreds of failed "Refreshing Blitz Cache" tasks. They all look like this:

```
14922	
O:42:"putyourlightson\blitz\jobs\RefreshCacheJob":7:{s:8:"cacheIds";a:0:{}s:10:"elementIds";a:2:{i:0;i:45038;i:1;i:45040;}s:12:"elementTypes";a:1:{i:0;s:48:"getdesigned\eventschedule\elements\EventSchedule";}s:10:"clearCache";b:1;s:11:"description";N;s:30:"craft\queue\BaseJob_progress";i:0;s:35:"craft\queue\BaseJob_progressLabel";N;}	
Refreshing Blitz cache	
1571985764	
99999	
0	
10	
2019-10-25 06:43:02	
1571985782	
0	
Checking 1 of 457 element queries.	
1	
1	
2019-10-25 06:43:02	
strpos() expects parameter 1 to be string, array given

```
Additional Info: the Class `getdesigned\eventschedule\elements\EventSchedule` is part of a customer specific extension written by our company, but the error provided on the last line does not help us much without being more specific.

Can you give us a hint on how to debug this?

**Comment by hiasl** [comment]
Additional info: We found this in the queue log:
```
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'strpos() expect...', '/data/www/k0039...', 1369, Array)
#1 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/db/QueryBuilder.php(1369): strpos(Array, '(')
#2 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/db/QueryBuilder.php(236): yii\db\QueryBuilder->buildGroupBy(Array)
#3 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\db\Query))
#4 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/db/Query.php(317): yii\db\Query->createCommand(Object(craft\db\Connection))
#5 /data/www/k003979/web/qss.esterhazy.at/vendor/craftcms/cms/src/db/Query.php(211): yii\db\Query->column(NULL)
#6 /data/www/k003979/web/qss.esterhazy.at/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1547): craft\db\Query->column(NULL)
#7 /data/www/k003979/web/qss.esterhazy.at/vendor/putyourlightson/craft-blitz/src/jobs/RefreshCacheJob.php(183): craft\elements\db\ElementQuery->ids()
#8 /data/www/k003979/web/qss.esterhazy.at/vendor/putyourlightson/craft-blitz/src/jobs/RefreshCacheJob.php(86): putyourlightson\blitz\jobs\RefreshCacheJob->_getElementQueryCacheIds(Object(putyourlightson\blitz\records\ElementQueryRecord), Array, Array)
#9 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2-queue/src/Queue.php(214): putyourlightson\blitz\jobs\RefreshCacheJob->execute(Object(craft\queue\Queue))
#10 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\queue\Queue->handleMessage('16907', 'O:42:"putyourli...', '99999', '1')
#11 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2-queue/src/cli/Command.php(145): yii\queue\cli\Queue->execute('16907', 'O:42:"putyourli...', '99999', '1', '')
#12 [internal function]: yii\queue\cli\Command->actionExec('16907', '99999', '1', '')
#13 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#14 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#15 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('exec', Array)
#16 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('exec', Array)
#17 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('queue/exec', Array)
#18 /data/www/k003979/web/qss.esterhazy.at/vendor/craftcms/cms/src/console/Application.php(93): yii\console\Application->runAction('queue/exec', Array)
#19 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('queue/exec', Array)
#20 /data/www/k003979/web/qss.esterhazy.at/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(craft\console\Request))
#21 /data/www/k003979/web/qss.esterhazy.at/craft(22): yii\base\Application->run()
#22 {main}
```

**Comment by putyourlightson** [comment]
The issue comes down to this line of code: https://github.com/yiisoft/yii2/blob/2.0.29/framework/db/QueryBuilder.php#L1369

This could indicate that you are requesting specific columns in a way that Yii doesn't recognise. Can you test this reducing the element query to something very simple? Feel free to share template code that results in the jobs failing.

**Comment by putyourlightson** [comment]
Any update on your side?

**Comment by hiasl** [comment]
No, not yet, but thanks for asking. We will have a look beginning of next week!

**Comment by spharion88** [comment]
I think I found the issue. The Query that is causing the problem uses a group by Statement with an Expression Parameter.

```php
->groupBy(new Expression('DATE_FORMAT(event_schedule.startDate, "%Y-%m-%d")'))
```

This gets serialized to the following JSON in `blitz_elementqueries` table. 

```json
{"expression":"DATE_FORMAT(event_schedule.startDate, \"%Y-%m-%d\")","params":[]}
```

And if this query gets deserialized it will be converted to an array instead of an Expression object which leads to the problem.

Is it possible that the RefreshCacheJob is not able to handle Expressions at the moment?

**Comment by putyourlightson** [comment]
Blitz uses the `json_encode` method to encode the query parameters, so once encoded, it cannot know what type of object should be created when it is decoded again. 

Can you rewrite your query to avoid use an object in the `groupBy` parameter? Some tweaking may be necessary, for example:
```
->select('DATE_FORMAT(event_schedule.startDate, "%Y-%m-%d") as startDate')
->groupBy('startDate');
```

**Comment by spharion88** [comment]
Thank you for quick reply.

We tried your workaround for the problem, but it doesn't work because the queries in the RefreshCacheJob are executed using the ids method `$elementQuery->ids()` and the ids method overwrites the select part of the query with `elements.id`.

A valid workaround for us was to overwrite the ids method in our custom query class and remove the groupby part from the query to be able to fetch element ids:
```
    public function ids($db = null): array
    {
        $this->groupBy = null;
        return parent::ids($db);
    }
```

The workaround is ok for now, but I think using Expressions and running queries that are not designed to return an element id are valid use cases and should be supported by Blitz.
Maybe a possibility to exclude specific queries from the cache would help too in this situation.

**Comment by putyourlightson** [comment]
Ok yes, I see what you did there. The problem with allowing objects in the query is that they can quickly bloat the database. The problem with excluding queries is that cache invalidation may become less reliable and we would like to avoid that. 

What does excluding the `new Expression` result in?
```
->groupBy('DATE_FORMAT(event_schedule.startDate, "%Y-%m-%d")')
```

**Comment by spharion88** [comment]
**The problem with allowing objects in the query is that they can quickly bloat the database.**
I think this wouldn't be different to now. JSON serializes public attributes of objects, so a large object would bloat the database with JSON too.
I would also restrict the serialization to Expression objects, because this is the only object that can be handled by Yii2 Queries (at least the only one I'am aware of).
A solution could also be to assume that arrays with the keys `expression` and `params` are Expression objects and get converted to Expressions during or after the deserialization.

**The problem with excluding queries is that cache invalidation may become less reliable and we would like to avoid that.**
I understand your point, but if I execute a query that can not handle element ids in the select part, then the query throws an exception in the `RefreshCacheJob` and I think that will also make the cache less reliable.

**What does excluding the new Expression result in?**
The group by without the `new Expression` doesn't work because Yii2 adds the quotes for database (grave accent) columns which breaks the query:

```
...
GROUP BY DATE_FORMAT(event_schedule.startDate, `"%Y-%m-%d")`
```

**Comment by putyourlightson** [comment]
> A solution could also be to assume that arrays with the keys expression and params are Expression objects and get converted to Expressions during or after the deserialization.

The `ExpressionInterface` is implemented by `yii\db\ActiveQuery, yii\db\ArrayExpression, yii\db\Expression, yii\db\JsonExpression, yii\db\PdoValue, yii\db\Query, yii\db\conditions\ConditionInterface`, plus any custom classes that implement `ExpressionInterface`, so we can't only look for `Expression` objects.

We would like to find the best and most flexible solution, but still ensure that performance and storage requirements of the invalidation process are as efficient and reliable as possible. 

If the only reason to use an `Expression` is for the double quotes then putting the expression in an array should work for you:

```
->groupBy(['DATE_FORMAT(event_schedule.startDate, "%Y-%m-%d")'])
```

From the [groupBy method docs](https://www.yiiframework.com/doc/api/2.0/yii-db-query#groupBy()-detail):

> The columns to be grouped by. Columns can be specified in either a string (e.g. "id, name") or an array (e.g. ['id', 'name']). The method will automatically quote the column names unless a column contains some parenthesis (which means the column contains a DB expression).

**Comment by spharion88** [comment]
You are right, a generic solution is not that easy.

Using the array does work for the group by part, thank you. But I think we will keep the solution where we overwrite the `ids` method. A query selecting element.ids grouped by a date wouldn't make sense anyway and also doesn't work with strict mysql settings.

**Comment by putyourlightson** [comment]
Ok sounds good, thanks for working through this with us!
