### ISSUE TITLE
Plugin: Solspace Freeform Cache Clearing

### ISSUE THREAD

**Issue by kiwidood** [putyourlightson/craft-blitz#209]
### Question
Currently when modifying a form using freeforms, the cache isn't cleared for the pages the forms are on. Is this functionality meant to work, or a feature that would be considered? Or do we need to create a custom plugin for this?

Thanks!

### Additional context

Potentially relevant config settings:

`'clearCacheAutomatically' => true,
'cacheElements' => true,
'cacheElementQueries' => true`

**Comment by bencroker** [comment]
Since forms in Freeform are _not_ elements, Blitz does not keep track of them. You have a few options available to you and I would recommend one of the following:

1. Put the form in a separate template and use the [dynamic content](https://putyourlightson.com/plugins/blitz#dynamic-content) feature in Blitz to fetch the contents of the template, using either `craft.blitz.getUri()` or `craft.blitz.getTemplate()`.

2. Exclude pages with forms on them from being cached, either using [excluded URI patterns](https://putyourlightson.com/plugins/blitz#included-excluded-uri-patterns) or [page specific options](https://putyourlightson.com/plugins/blitz#page-specific-options):
`{% do craft.blitz.options.cachingEnabled(false) %}`

**Comment by kiwidood** [comment]
Thanks for your help. I decided to use a custom module to handle cache invalidation.

For anyone wanting to do the same, you can use this event: Solspace\Freeform\Services\FormsService::EVENT_AFTER_SAVE
and then putyourlightson\blitz\Blitz::$plugin->refreshCache->refreshCachedUrls($array);

**Comment by bencroker** [comment]
Nice, thanks for posting how ou did it!
