### ISSUE TITLE
Edit links using getTemplate seems overkill

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-blitz#238]
### Question
My client has a directory site you're familiar with. They have paginated listing pages and beside each entry that appears on the page I added an Edit Link icon so they can click directly to open URL in the control panel

The method I used is to add `{{ craft.blitz.getTemplate('_macros/quickEdit', { entryId: self.id }) }}`
Inside the macro just some logic to make sure its an admin viewing the link.

There is an issue I believe at busy times with apache processes as each page could be calling this template up to 20 times. When public see it though it's just an empty template as it won't show to non-admins but I'm still getting the hit of these requests.

Can you offer any advice here?

Alos to say Bingbot etc seems to be following these links too

Craft CMS 3.4.25
Blitz 3.6.5

**Comment by bencroker** [comment]
This certainly isn't ideal, but from the sounds of what you want to do, at least one AJAX call needs to be made to the server to get the dynamic content. Since you most likely don't want to require an AJAX call to load all of the entries (without caching them), I think that using [Sprig](https://putyourlightson.com/plugins/sprig) for this would be an ideal use-case. Look at the [dynamic content](https://putyourlightson.com/sprig-cookbook#dynamic-content) and [pagination](https://putyourlightson.com/sprig-cookbook#pagination) examples for reference and your component might look something like below. This will output the entries in the first page load (which will get cached) and then with and AJAX request update the entries adding the edit links only if the user is an admin.

```twig
{% if sprig.request and not currentUser.isAdmin() %}
    {# Exit without updating the content #}
    {% exit 204 %}
{% endif %}

{% set entries = craft.entries.all() %}

<div sprig s-trigger="load">
    {% for entry in entries %}
        {{ entry.title }} 
        {% if sprig.request and currentUser.isAdmin() %}
            <a href="{{ entry.cpUrl }}">Edit</a>
        {% endif %}
    {% endfor %}
</div>
{% endif %}
```

**Comment by john-henry** [comment]
Hi @bencroker I have tried Sprig here and while the concept seems simple, the nature of how the Sprig includes work with not inheriting variables etc would require a good bit of re-architecture on this end.

Question for you which may or may not be a useful feature. Can there be a parameter for that would only fetch template if logged in or had a certain cookie

So if there was a method like `getAdminTemplate` that would only fetch the template if the user was logged in/admin
`{{ craft.blitz.getAdminTemplate('_macros/quickEdit', { entryId: self.id }) }}` thus saving on all the empty requests

Do you think this is an edge case?

**Comment by bencroker** [comment]
I do think it is rather edge case and I'm not even sure that it is possible to determine whether a user is an Admin based on the value of a cookie.
