### ISSUE TITLE
blitz can't support webp

### ISSUE THREAD

**Issue by bzkjyf** [putyourlightson/craft-blitz#273]
### Describe the bug
blitz cache can't support webp?

- Plugin version:3.6.11
- Craft version:Craft 3.5.15.1

**Comment by bencroker** [comment]
Blitz caches a page's output. If the output contains a `webp` file then it will be cached, otherwise it will not.

**Comment by bzkjyf** [comment]
> Blitz caches a page's output. If the output contains a `webp` file then it will be cached, otherwise it will not.
hi:
thank u. but, each page has 'webp' file, how can i setup blitz? i need webp file and cache page...

**Comment by bencroker** [comment]
Like I said, if the page outputs a `webp` image then it will be cached. I'm not following what the problem is, can you please explain?

**Comment by bzkjyf** [comment]
hi:
the twig code is:
{# If the client has support for WebP, create WebP images, if not, use default #}
{% set imageSizes = [{ width: 600 }, { width: 800 }, { width: 1000 }, { width: 1200 }] %}
{% if craft.imager.serverSupportsWebp() and craft.imager.clientSupports('webp') %}
    {% set transformedImages = craft.imager.transformImage(image, imageSizes, { format: 'webp' }) %}
{% else %}
    {% set transformedImages = craft.imager.transformImage(image, imageSizes) %}
{% endif %}

{# Output picture element with a separate source for clients that support WebP #}
<img src="{{ craft.imager.base64Pixel() }}" sizes="100vw" srcset="{{ craft.imager.srcset(transformedImages) }}">

if blitz Caching Enabled but it can't output webp, only jpg? Disable and it's  work~ What's the problem?

**Comment by bencroker** [comment]
The problem is that Blitz is caching your output, so you cannot expect an if/else statement to work. Instead of doing it this way, you should use the `picture` tag to output `webp` as well as other image formats and let the user's browser decide which image to use.

This is explained in the [ImagerX docs](https://imager-x.spacecat.ninja/usage/webp.html#delivering-webp-images-to-your-users) along with the following example:

```twig
{# Output picture element with a separate source for clients that support WebP #}
<picture>
    {% if craft.imager.serverSupportsWebp() %}
        <source sizes="100vw" srcset="{{ craft.imager.srcset(transformedImagesWebp) }}" type="image/webp">
    {% endif %}

    <img src="{{ craft.imager.base64Pixel() }}" sizes="100vw" srcset="{{ craft.imager.srcset(transformedImages) }}">
</picture>
```

It is fine to keep the `craft.imager.serverSupportsWebp()` as the value that is returned should never change, since this is a server check.
