### ISSUE TITLE
Using Blitz with native Craft cache tags

### ISSUE THREAD

**Issue by bryantAXS** [putyourlightson/craft-blitz#279]
### Question
I'm curious how well Blitz plays with Craft's native cache tags?

As a hypothetical example, our pages have 3 main sections of content, each which is ideally broken at different times.

- Navigation, twice a day
- Page Content, once an hour
- Footer, once a day

In theory I could setup Blitz to refresh the cache once and hour, which would satisfy breaking the Page Content section, and then hypothetically I use native Craft tags for continuing to cache the Navigation and Footer content based on their own schedules.

In that scenario, each our hour the Page Content would refresh, and depending on the hour of the day the Navigation and Footer days may or may not refresh.

If that's not possible, what is a good way to handle this type of "partial" caching?

### Additional context
In this scenario I'm assuming all automatic cache breaking based on element queries is disabled.

**Comment by bencroker** [comment]
This sounds like a rather complex setup to have to keep track of. Any reason you're not just leaving it to Blitz to intelligently refresh the cache when necessary?

**Comment by bryantAXS** [comment]
Because of the architecture of our site and CMS, every time we were saving an entry, it was triggering hundreds of pages to be warmed, and creating a huge server performance issue. Thus, we turned off `cacheElementQueries` and `cacheElements` and are breaking all the caches manually.

**Comment by bencroker** [comment]
Blitz caches entire pages, caching partials is not possible, so to satisfy your criteria would mean refreshing the cache every hour. It sounds, however, like the issue is more to do with how many elements are related to each other. I would recommend enabling the `cacheElements` setting, as that is responsible for a large part of what Blitz does, and then decoupling things like navigation sections using a dedicated navigation plugin, for example.
See https://putyourlightson.com/plugins/blitz#the-entire-cache-is-cleared-and-warmed-when-only-one-entry-is-updated

**Comment by bryantAXS** [comment]
Thanks for the quick responses, Ben!

One thing that would help is a little better explanation on what `cacheElements` and `cacheElementQueries` do more specifically, and in what cases you would use them and/or one and not the other?

I know you reference it inside your documentation, but the explanation itself is pretty vague and nearly identical for both of them. It seems like one is used for creating new elements and one is used for updating existing elements. Is that true? Aside from that, do they have any difference?

I did some digging and found this thread (https://github.com/putyourlightson/craft-blitz/issues/175) but it's still a little unclear.

My understanding is that by default, all elements on a page are cached, so that if an entry/element is saved in the CMS, all pages that have that cached entry/element within it would be refreshed. When you use disable `cacheElements` and `cacheElementQueries` any entries/elements inside that block of content are **not** cached, and thus won't trigger the page to be refreshed. 

So in theory, with the code below, the any entries/elements within the Header, Navigation, and Footer sections of the website wouldn't be cached, and thus cause a page's cache to be broken. In this case only entries/elements inside the Content section would. Is that correct?

```
{% do craft.blitz.options.cacheElements(false).cacheElementQueries(false) %}
[Header]
[Naviagtion]
{% do craft.blitz.options.cacheElements(true).cacheElementQueries(true) %}

[Content]

{% do craft.blitz.options.cacheElements(false).cacheElementQueries(false) %}
[Footer]
{% do craft.blitz.options.cacheElements(true).cacheElementQueries(true) %}
```

In term of caching partials, the thing I'm struggling with is... Let's say we have 2000 articles in the CMS all of which share a navigation that takes 150 queries. If we break and warm the cache on all 2000 articles at the same time, that navigation section is going to take up 150 queries for each article, when technically it's going to produce the same result.

Is there any approach for getting around this, to avoid having the server get hammered if the cache is broken/warmed like this?

^ This is what I'm trying to work around with the native Craft CMS caching.

I realize this is a long post, but just trying to wrap my head around everything. Thanks!

**Comment by bencroker** [comment]
> I know you reference it inside your documentation, but the explanation itself is pretty vague and nearly identical for both of them. It seems like one is used for creating new elements and one is used for updating existing elements. Is that true? Aside from that, do they have any difference?

- `cacheElements` is required for keeping track of the elements used on a page, which is used for cache invalidation of pages when elements used on those pages are _updated or deleted_.
- `cacheElementQueries` is required for keeping track of the element queries used on a page, which is used for cache invalidation of pages when _new elements are added_ that should appear on those pages.

> In term of caching partials, the thing I'm struggling with is... Let's say we have 2000 articles in the CMS all of which share a navigation that takes 150 queries. If we break and warm the cache on all 2000 articles at the same time, that navigation section is going to take up 150 queries for each article, when technically it's going to produce the same result.

The fact that 150 queries are required to output a navigation should be setting off alarm bells. Normally it should require only several, which would seem to indicate that the site needs some fundamental optimisations to be made. Right now you are using Blitz more like a band-aid for a sub-optimal architecture, which is compounding your issues and forcing you to look for complex workarounds. 

The most obvious optimisation is in the navigation. I would start with the recommendations as explained here, otherwise you'll  find yourself in a in uphill battle:
https://putyourlightson.com/plugins/blitz#the-entire-cache-is-cleared-and-warmed-when-only-one-entry-is-updated

**Comment by bryantAXS** [comment]
> Normally it should require only several, which would seem to indicate that the site needs some fundamental optimisations to be made. Right now you are using Blitz more like a band-aid for a sub-optimal architecture, which is compounding your issues and forcing you to look for complex workarounds.

This is a hypothetical example with hypothetical query number associated to it, Ben. I'm using it simply to ask if there are more sophisticated ways to handle the caching of query-intensive parts of a site, rather than a one-size-fits-all approach.

It sounds like the answer is "No" so I just leave it at that.

**Comment by bencroker** [comment]
Ah I see, sorry about the confusion. 

In that case, you hypothetically could use Craft cache tags within a page cached by Blitz, while excluding element queries from partials of that page. But in practice this sounds like a nightmare to maintain and troubleshoot down the line. 

So I guess the answer depends on your pain threshold and how much technical debt you are ok with taking on.
