### ISSUE TITLE
Blitz Cache Utilities disabled

### ISSUE THREAD

**Issue by sarahschuetz** [putyourlightson/craft-blitz#283]
After updating Craft CMS to 3.5.17.1, updating Blitz Plugin to 3.7.0 and enabling project.yaml, I can no longer use the Blitz actions in the Blitz Cache Utilities because they are all disabled.
Caching is working fine though.

- I am an admin user so I should have the correct permissions
- Caching is enabled
- I enabled allowAdminChanges to check if any of the settings are different, but they are all the same as before the update and switching to project.yaml
- In my Blitz config file I just set excludedQueryStringParams explicitly

What am I missing here? What could cause the Blitz Cache Utilities to be disabled?

**Comment by bencroker** [comment]
What exactly do you mean by "disabled"? If it is visual then can you please share a screenshot?

**Comment by sarahschuetz** [comment]
All submit buttons have a class `disabled` and therefore are not clickable.

<img width="947" alt="Screenshot 2021-01-20 at 20 39 26" src="https://user-images.githubusercontent.com/14288451/105226086-ce886c80-5b5f-11eb-837c-589328f9d829.png">

**Comment by bencroker** [comment]
I'm struggling to see where the plugin might be adding a `disabled` class. Do you have any custom modules or plugins that might be adding this?

**Comment by sarahschuetz** [comment]
Our custom module only hast some php stuff, no javascript and nothing control panel relevant. However I will try disabling other plugins and check if there is another plugin interfering.

Thanks for your input so far

**Comment by bencroker** [comment]
Ok, let me know what you find.

**Comment by sarahschuetz** [comment]
Okay seems to be an issue with the newest version of the CP Clear Cache plugin which seems to add the disabled classes. As soon as I disable the plugin, the buttons work fine. Guess I have to open an issue there. Thanks! :)

**Comment by mmikkel** [comment]
The problem here, is that CP Clear Cache needs to instantiate Craft's Clear Caches utility JS on all pages inside the CP – this used to be safe to do, because the utility was sandboxed to a single form identified by ID, but since [this commit](https://github.com/craftcms/cms/commit/5f3a845277611d4c8b0890ffc271f160008f98bb#diff-e2a01e12aedc66a3d64e7a3a62232580d8c6093a20a7d149b37a3068bc7a77a6) the utility actually instantiates on all forms with the CSS classname `utility` – which is where we run into trouble re: Blitz' clear caches utility form.

Not sure if I'd call it a Craft bug or not – the Clear Caches utility works as intended on their end and what CP Clear Cache does is technically a hack/using undocumented features. In any case, I'll have a think and try to think of a workaround.

**Comment by bencroker** [comment]
Ok, thanks for the note!
