### ISSUE TITLE
Error when using local warmer

### ISSUE THREAD

**Issue by benface** [putyourlightson/craft-blitz#305]
### To reproduce
Steps to reproduce the behaviour:
1. Set the "Cache Warmer" setting to "Local Warmer".
2. From the Blitz utility, click on "Refresh Cache".
3. Notice the queue job that gets created fails instantly, with the following error message:

> Argument 1 passed to putyourlightson\blitz\services\GenerateCacheService::save() must be of the type string, null given, called in /app/vendor/putyourlightson/craft-blitz/src/drivers/warmers/LocalWarmer.php on line 164

### Expected behaviour
No error.

### Versions
- Plugin version: 3.8.0
- Craft version: 3.6.12

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/de6d2de6d5f119af33ccc7e708cc7861ca13fe5f. Note that the local warmer is less stable than the Guzzle warmer. It will likely be refactored in Blitz 4 to be the default warmer, but Yii makes mocking a request rather clunky, so in the meantime the Guzzle warmer is recommended unless using a headless setup.

**Comment by bencroker** [comment]
Released in version 3.9.0.
