### ISSUE TITLE
How is this different and more performant than fastCGI?

### ISSUE THREAD

**Issue by hisnameisjimmy** [putyourlightson/craft-blitz#31]
Just curious, since we implement fastCGI. Main issue we have with fastCGI currently is that we can't clear cache for just a specific entry on save, instead wiping the whole site cache.

**Comment by putyourlightson** [comment]
Right, one big advantage of Blitz is that because it has access to your site's element events, it can intelligently invalidate and then warm only the URLs that need to be refreshed. This is itself makes using it more performant on sites with a large number of URLs as the server load is never larger than necessary. And because it warms your cache too, no poor users will be left waiting for uncached pages to load.

**Comment by hisnameisjimmy** [comment]
But I would imagine it doesn't load into memory or have some of the other benefits of fastCGI.

**Comment by putyourlightson** [comment]
No, it doesn't load into memory, it creates statically cached files which when used with a server rewrite result in very fast pageloads and low server processing. The benefits of the Blitz plugin are really its ease of use and setup along with intelligent cache invalidation.

**Comment by hisnameisjimmy** [comment]
I would pay significantly for something that did intelligent cache
invalidation with fastCGI.

**Comment by putyourlightson** [comment]
The [FastCGI Cache Bust plugin](https://github.com/nystudio107/fastcgicachebust) will clear the entire cache but I don't know of any plugin that will do it intelligently.
