### ISSUE TITLE
cpliakas/git-wrapper is abandoned

### ISSUE THREAD

**Issue by D3strukt0r** [putyourlightson/craft-blitz#362]
### Describe the bug
"Package cpliakas/git-wrapper is abandoned, you should avoid using it. Use symplify/git-wrapper instead."

https://github.com/putyourlightson/craft-blitz/blob/develop/composer.json#L21

### To reproduce
Steps to reproduce the behaviour:
1. Add plugin to composer.json
2. Install libraries

### Expected behaviour
No warning, just install.

### Screenshots
<img width="766" alt="grafik" src="https://user-images.githubusercontent.com/5726865/147229080-999cfe6c-0b18-4a45-8e51-3f342b4a5f04.png">

### Versions
- Plugin version: 3.11.0
- Craft version: 3.7.26

**Comment by bencroker** [comment]
Unfortunately, `symplify/git-wrapper` requires PHP 8.0 and above: https://github.com/symplify/git-wrapper/blob/302d258d5744fac5aee816704bdf63ea5c08b79e/composer.json#L7

Since Craft only requires PHP 7.2.5 and above, switching from `cpliakas/git-wrapper` to `symplify/git-wrapper` is not an option at present.

More background info at https://github.com/cpliakas/git-wrapper/issues/225

**Comment by bencroker** [comment]
More background info at https://github.com/cpliakas/git-wrapper/issues/225
