### ISSUE TITLE
Best approach for using Remote Deployer with a large number of static assets?

### ISSUE THREAD

**Issue by mgburns** [putyourlightson/craft-blitz#376]
### Question
We're evaluating Blitz w/ Remote Deployment to create a completely static site. One wrinkle we foresee is using the Git Provider with a large number of media assets. Is Git LFS the best way to get around this? If so, what's the best way to make the Git Wrapper used by the Remote Deployer aware of the Git LFS binary when it needs to be installed in userland? (We don't have write access to to`/usr/local/bin` or any other global bin directories on our VPS so we need to install it in the home directory and modify the PATH via shell profile).

### Additional context
We've ruled out using remote volumes for media as it creates the risk of discrepancies between the assets present on the remote volume and the ones uploaded during the most recent remote deployment. We're open to alternative Remote Deployer solutions, but want it to be as "atomic" as possible when deploying to prevent any downtime when a deployment is in process due to dependencies across files.

**Comment by bencroker** [comment]
Git isn't ideal for large numbers of media assets, unless you specifically need them version controlled. What I'd recommend in this scenario is figuring out how to leverage remote volumes so that they work for you. The advantage in using remote volumes, of course, is that the media files are decoupled from your site, so no assets will be committed via Git, thereby decreasing deployment time and making things more robust in general.

**Comment by mgburns** [comment]
@bencroker Totally missed your (very fast) response! Thanks for that context. It's not a huge site, but definitely big enough to run up against GitHub repo size limits. We're giving [Netlify Large Media](https://docs.netlify.com/large-media/overview/) (which uses Git LFS under the hood) a try and happy so far.

**Comment by bencroker** [comment]
Sounds good!
