### ISSUE TITLE
Editing/updating robots.txt in SEOMatic triggers a full cache refresh

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-blitz#380]
### Describe the bug
Editing/updating robots.txt in SEOMatic triggers a full cache refresh (and warm) in Blitz

### To reproduce
Steps to reproduce the behaviour:
 Go to "Global SEO" -> "Robots" and edit the content and save

### Expected behaviour
Just to update the robots.txt file

### Versions
- Plugin version: 3.9.0
- Craft version: 3.6.15

**Comment by bencroker** [comment]
It looks like saving any global setting in SEOmatic triggers an invalidation of all of the meta container caches, which then triggers a full refresh of the Blitz cache via the `EVENT_INVALIDATE_CONTAINER_CACHES` event:
https://github.com/nystudio107/craft-seomatic/blob/362029c7095931150c65b3dbf957b14393f4e3f4/src/services/MetaContainers.php#L919-L940

Perhaps @khalwat can enlighten us as to whether this is intentional?

**Comment by khalwat** [comment]
It's intentional, but it's perhaps a bit heavy-handed in some cases. Probably editing the various frontend templates doesn't require all of the meta caches to be invalidated.

Since the "General" settings is one big form, there's one controller endpoint that handles the saving of those settings. Some settings in General do require a full invalidation, so the only way to make this less heavy-handed would be to somehow do a diff of the changes, and then figure out which ones require a full cache invalidation, and which ones don't.

In general, as you know, I'm not a huge fan of "warming" caches in general (there are some specific circumstances where it makes sense, but they are not too common).

**Comment by bencroker** [comment]
Thanks for clarifying, @khalwat. So the conclusion is that this is a feature, not a bug.
