### ISSUE TITLE
Disable cache for any (or some) logged in users

### ISSUE THREAD

**Issue by grafixgeek** [putyourlightson/craft-blitz#453]
I believe that the cache is disabled when the logged in user is admin, and has front end debug turned on. It would be nice to have the option to turn cache disabling on for all logged in users (without debug), or perhaps more sensibly, just those in specific user groups.

Reason being is that I have very large structures and channels (over a 1000 pages) and a page update triggers a full structure cache clearance. This takes several minutes and while this is happening more may back up. During this time none of the content editors can see their refreshed page (getting them to add a fake query string is too hard it seems).

I realise there are a bunch of workarounds, but this would be a really nice solution for plugin users that have this problem.

**Comment by bencroker** [comment]
> It would be nice to have the option to turn cache disabling on for all logged in users

It's not possible to do so, due to that requiring PHP to be executed and we can't be sure that the request will even reach Craft (if using server rewrites or a reverse proxy). 

> Reason being is that I have very large structures and channels (over a 1000 pages) and a page update triggers a full structure cache clearance.

An entry update is what triggers page refreshes. If an entry is used on all 1,000 pages then yes, it may result in a large refresh, which is why we suggest some [workarounds](https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up), but an already performant site should work well by default and we have a new feature in the pipeline that should help with this too in the [4.3.0 branch](https://github.com/putyourlightson/craft-blitz/tree/4.3.0). Several minutes sounds extremely long so I suggest you use the [Hints utility](https://putyourlightson.com/plugins/blitz#hints-utility) to find eager-loading opportunities.

> During this time none of the content editors can see their refreshed page (getting them to add a fake query string is too hard it seems).

Content editors can use the Preview feature of entries to see changes before (and after) publishing changes.

**Comment by grafixgeek** [comment]
Thanks for the reply - I guess I should have realised about the PHP thing
(duh!)

I'll look at your suggestions.
