### ISSUE TITLE
Feature request: Release previous caching jobs before generating cache

### ISSUE THREAD

**Issue by jorisnoo** [putyourlightson/craft-blitz#454]
Hi, - and first of all, thank you very much for all your effort on this great plugin!

i'm using blitz on a site with a few thousand pages, so generating the full cache is taking some to finish.
This is generally no issue, except in some cases:
1. on each deployment, the cache is flushed and newly generated. if there are, however, a few consecutive deployments, they result in multiple (possibly overlapping) jobs in the queue that generate the cache. some of them usually tend to time out and fail
2. when editors make a lot of changes to the site, the same appears to happen: the queue is piling up with blitz jobs — which end up blocking other jobs in the queue from running

i was therefore wondering, whether it'd somehow be possible to release all blitz jobs from the queue before starting to (re-)generate the cache; or if there was any other way to prevent this from happening?

Thank you very much for your help!

Craft CMS Pro 4.3.1
Blitz 4.2.3

**Comment by bencroker** [comment]
When you say "deployment", what kind of setup are you referring to?

What you're asking is not as trivial as it sounds, because saving an entry can affect pages which may be different to the pages changed by saving another entry. If we're talking about generating the _entire_ cache then you may have a point, I'll need to look into it further though, as there are lots of pieces to this puzzle and some things have to happen in a certain order.

**Comment by jorisnoo** [comment]
@bencroker Thanks for your prompt response!

Sorry, by "deployment" i meant deploying updates of the codebase to the staging or production server. Eg. when twig templates are changed and those changes are deplyoed to the server, the whole blitz cache is cleared.

I see your point. For my case, it'd already be very helpful, if running `php craft blitz/cache/refresh --queue=1` from the console would first release all running blitz jobs (since the entire cache is rebuilt, correct?). Or exposing another console command to clear all blitz jobs, that could be run before that one, would also work just as well. Is this something you'd consider looking into? Many thanks!

**Comment by bencroker** [comment]
Yeah I can look into which approach makes the most sense, thanks for the suggestion!

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/8d179d1cb4c3f0e0cf27fd7b9922a0a9328aeb8e for the next release. Note that this will only work when cache clearing is enabled, as otherwise the cache generation jobs need to be allowed to complete, since they are responsible for regenerating expired cache.

**Comment by jorisnoo** [comment]
Thank you! 🙌

**Comment by bencroker** [comment]
Just released in version 4.3.0.
