### ISSUE TITLE
PHP 8 Error "Cannot access offset of type string on string" in Cache Request Service

### ISSUE THREAD

**Issue by martinhellwagner** [putyourlightson/craft-blitz#468]
We recently upgraded from PHP 7.4 to 8.0 and are now getting the Error "Cannot access offset of type string on string" on Line 406 in the `CacheRequestService.php` file in Blitz. This seems to be a problem related to the `if` statement and the new PHP version. Any idea how this can be fixed?

**Craft CMS:** 4.3.6.1
**Blitz Plugin:** 4.2.3

![Screenshot 2023-01-31 at 13 49 10](https://user-images.githubusercontent.com/19146752/215765826-2d3dc9ca-7da4-495d-afed-1e0467ca020d.png)

**Comment by bencroker** [comment]
Can you please check the values of `includedQueryStringParams` and `excludedQueryStringParams` in the Blitz config file, assuming you have them in there? The format changed in Blitz 4 and it's possible that you may not have updated the values. 
https://github.com/putyourlightson/craft-blitz/blob/a4ed151178323344a4f388ceadc553e85143347b/src/config.php#L146-L164

Otherwise, check the values in the plugin settings under the Advanced tab.

**Comment by martinhellwagner** [comment]
@bencroker

Thanks for getting back to me so quickly! They were indeed in the wrong format – I've updated the structure, and now everything works fine again. 🙂 

Should "All sites" be denoted as `'siteId' => '*'`, or is `'siteId' => ''` also possible?

**Comment by bencroker** [comment]
Great! `'siteId' => ''` should be used for all sites.

**Comment by martinhellwagner** [comment]
Done. Thanks again! 🚀
