### ISSUE TITLE
Incorrect paginated URLs when triggering generate from CP

### ISSUE THREAD

**Issue by Wiejeben** [putyourlightson/craft-blitz#469]
Hi there!

Today we noticed that when we press the "Generate Cache" button from the CP the paginated URLs are incorrect. I did some debugging and it looks like the `pageTrigger` configuration from the GeneralConfig isn't loaded the moment that the Generate Cache job is added to the queue.

I did a `dd(...)` inside `\putyourlightson\blitz\helpers\SiteUriHelper::getPaginatedUrisForSite(...)`, when executing `php craft blitz/cache/generate` from terminal the URLs are as follows
- news?p=2
- news?p=3

However when I trigger the same function via the Generate Cache button it becomes the default:
- news/p2
- news/p3

Versions:
Craft 4.3.6.1
Blitz 4.2.3
PHP 8.1.11

**Comment by bencroker** [comment]
I'm looking into this, but Blitz should always fetch the `pageTrigger` from the general config settings.

**Comment by bencroker** [comment]
I managed to track this down to these lines in Craft's web request class:
https://github.com/craftcms/cms/blob/9b483fafa5deaf1cd3df73a636ec73a908295204/src/web/Request.php#L307-L311

Since the utility runs as a CP action request, the page param is reset to `p`, which seems unnecessary according to the comment.

I've reported this in https://github.com/craftcms/cms/issues/12598 and hopefully will get a response soon.

**Comment by Wiejeben** [comment]
Interesting, great discovery! Not sure how they would solve this without potentially breaking a whole lot of plugins since `pageTrigger` was always overwritten for CP routes. I'll keep an eye on https://github.com/craftcms/cms/issues/12598.

**Comment by bencroker** [comment]
This should be resolved in the next versions of Craft 3 and 4, see https://github.com/craftcms/cms/issues/12598.

**Comment by bencroker** [comment]
Craft 3.7.64 and 4.3.7 have been released with that change.
