### ISSUE TITLE
Don't fire queue job if caching is disabled

### ISSUE THREAD

**Issue by sjelfull** [putyourlightson/craft-blitz#47]

**Comment by putyourlightson** [comment]
I'm guessing that you're referring to a "Refreshing Blitz Cache" queue job? Even with caching disabled, this is important in order to clear stale cache when an element is modified.

**Comment by sjelfull** [comment]
I'd like a way to disable that regardless. It creates a bunch of queue jobs even though its pointless in an environment where we aren't using the cache (say, locally).

Those in turn causes other issues.

**Comment by putyourlightson** [comment]
Disabling the plugin is always possible...

**Comment by sander-lameco** [comment]
Is there another way next to disabling the plugin entirely to bypass the queue jobs?
As you said it is to clear stale cache, so if we empty the cache table in the DB will it skip the queue jobs?

Now it is blocking a lot of other queue jobs that are actually needed because we added a new site to the multi-site setup and it has to Resave all entries is every section.

**Comment by bencroker** [comment]
This issue has been closed for years. Please open a new issue with a clear description and I can respond in more detail there.
