### ISSUE TITLE
Cache files not updating on multi-site 

### ISSUE THREAD

**Issue by grafixgeek** [putyourlightson/craft-blitz#488]
I'm not entirely sure this is a bug but I have replicated it. First on a production site (Craft 3.7.50 & Blitz 3.12.6) and then on a local install on a Mac (Craft 4.4.5 & Blitz 4.4.3). The second (non-primary) site is on a different domain, and has a different web document root folder that sits alongside that of the primary site. I think all other settings are default (like Cache Storage, Cache Generator). When Blitz caching is turned on and a URI pattern is set up the cache files are correctly written to @webroot/cache/blitz and when I call these files via the browser I can see the Blitz comments. So far so good. However, when I edit the template, or update the entry for the file, then the cache files are updated on the primary site, but not on the secondary site. Even when I do a full cache refresh the secondary site cache files are not updated. The file permissions and configs for both sites are identical. If I delete the cache files on the secondary site then new ones are correctly written, but they in turn will not update. As I suggested above this happens with a simple "Hello world" template (i.e. no database calls), or with a regular page that calls entries from the database. I also turned on blitz.log but nothing of note shows up there. The logs report successful refresh when everything is done, or even when secondary site only is done, when in fact the files are not updating. Hope you have some ideas? :)

**Comment by bencroker** [comment]
It sounds like something might be incorrectly configured for the secondary site, or this might just be a bug. If you can send a database dump as well as your project’s `composer.json` file to info@putyourlightson.com then I’ll try to replicate this locally so I can troubleshoot the specific issue.

**Comment by bencroker** [comment]
After troubleshooting this locally, it turns out that the issue was due to two unique webroots being used. The cache folder path is intended to be an absolute path whereas the `@webroot` alias, if not explicitly defined, can differ in value based on the site and in the case of console commands may be undefined. Using a relative path is not recommended, as its behaviour can be less deterministic. For this use-case, the Yii Cache Storage driver will be the most robust solution, which is also what is recommended for sites with ephemeral storage. If speed is a concern then I’d suggest you use a reverse cache proxy such as Cloudflare. I hope this helps explain and resolve the issue for you.
