### ISSUE TITLE
craft.blitz.includeDynamic - getting entry variables and custom fields

### ISSUE THREAD

**Issue by sander-lameco** [putyourlightson/craft-blitz#506]
We tried implementing using `craft.blitz.includeDynamic('templates/includes/header.twig', { entry: entry }`.
In the included template we have stuff like `entry.url` and `entry.vacancyId` but these keys aren't existing in the array of data.

Is there data missing or how does this work? Should we push all these required data in the include instead of just the `entry`?

**Comment by bencroker** [comment]
Since requests are made via AJAX, only primitive data types should be passed in as parameters: strings, numbers, booleans and arrays. Objects, models and elements cannot be used. If you want to pass an element (or set of elements) into a dynamic include then you should pass in an ID (or array of IDs) instead and then fetch the element from within the template.

```twig
{{ craft.blitz.includeDynamic('templates/includes/header.twig', { entryId: entry.id }) }}
```

Then inside the dynamic include template:
```twig
{% set entry = craft.entries.id(entryId).one() %}
```

I’ve made a note of this in the docs at https://putyourlightson.com/plugins/blitz#craft-blitz-includedynamic

**Comment by sander-lameco** [comment]
Ah yeah that seems to work except it keeps giving me eager-loading hints even though I'm eager-loading the desired fields inside the included template using:

```
{% do craft.app.elements.eagerLoadElements(
    className(vacancyGlobals),
    [vacancyGlobals],
    [
        ['globalHeaderImages', {withTransforms: ['headerVisual']}],
        ['globalHeaderImagesMobile', {withTransforms: ['headerVisualMobile']}],
        'vacancyLanguage'
    ]) %}
```

> Some context, these fields are coming from a global set and not from the entry.

Maybe I'm missing something here.

![Screenshot 2023-05-17 at 09 20 24](https://github.com/putyourlightson/craft-blitz/assets/25500086/ee7c81c1-24e2-43d3-8feb-f4aa6eca24e1)

**Comment by bencroker** [comment]
That’s good to hear. Regarding eager-loading, I can’t help you with this without seeing and understanding your templates, which is beyond the scope of Blitz support.
