### ISSUE TITLE
How do I prevent cached content for logged in users?

### ISSUE THREAD

**Issue by airidasbrikas23** [putyourlightson/craft-blitz#552]
I have specific parts of HTML displayed only for logged in users. I can prevent that from making it into the cache, but once non logged in user enters the website, then the cached content is being output to logged in users, while it should not. How do I prevent that?

**Comment by bencroker** [comment]
In this kind of situation, you’d probably be best off using the [`includeDynamic`](https://putyourlightson.com/plugins/blitz#craft-blitz-includedynamic) tag which will allow the included template to be rendered dynamically before being injected into the page.

```twig
{{ craft.blitz.includeDynamic('path/to/template') }}
```

**Comment by airidasbrikas23** [comment]
Thank you!

**Comment by airidasbrikas23** [comment]
Hi,

But then if I absolutely all content to skip cache for logged in users, I would have to add my whole code into includeDynamic, for all templates, potentially having to duplicate them all. This would create a lot of complexity.

My problem, is that there is lag for how long it take for Blitz to clear its cache and that strongly degrades editor experience. 

What are other ways to do that?

**Comment by bencroker** [comment]
I’m not exactly sure what you're asking. You can do more advanced things in terms of dynamic content with Sprig, see the livestream at https://craftquest.io/livestreams/dynamic-content-on-statically-cached-pages

**Comment by airidasbrikas23** [comment]
This adds even more complexity. I just need Blitz to not deliver any cached content to logged in users. Not specific parts, but the whole website code, global.

**Comment by bencroker** [comment]
It’s important to keep in mind that Blitz uses full static page caching and determines whether to cache pages based on their URI. So conditionally displaying cached pages based on the user session is not possible. 

What you could potentially do s a workaround is add a prefix to the URL for logged in users and use an excluded URI pattern to prevent those pages from being cached. So, for example, guests might see links that point to `welcome` whereas logged in users might see links that point to `member/welcome`. You can set things up so that the same template is used to render both URIs, but exclude the latter from caching using the pattern `^member/.*`.
