### ISSUE TITLE
Cache refresh not triggered when saving/updating Verbb Events Plugin elements

### ISSUE THREAD

**Issue by jarheadcore** [putyourlightson/craft-blitz#572]
**Description**

Using Verbb's events plugin in combination with Blitz nginx caching to get super fast cached event pages. Saving Craft entries triggers a cache refresh queue job when caching is enabled. This behavior is expected as well when saving a Verbb event unless the events are excluded via the “nonCacheableElementTypes" setting.

**Reproduction**
- Install the Verbb Events Plugin
- Enable nginx level caching in Blitz
- Edit e.g. the title or a custom “eventDescription” textfield of an event

**Expected Behavior**
Saving this event should trigger a cache refresh queue job + a refreshed frontend showing the edited event. 

Note:
If an entry in a entry field relation (e.g. speaker of the event from a craft channel “speakers”) is saved, the job queue gets run.

**Installed Versions**
- Craft 4.5.7
- Verbb Events Plugin 2.0

Note:
“dev-craft-4 as 2.0.0” with Verbb’s fix “trackChanged()” implemented does not seem to resolve the issue.

**Basic Demo Project showing the behavior here:**
https://github.com/jarheadcore/craft-blitz-events

**Comment by bencroker** [comment]
Thanks for the detailed report! This turned out to be an issue with Blitz not recognising the Event element’s `live` element status. I’ve changed the behaviour in https://github.com/putyourlightson/craft-blitz/commit/37889209b36888e535ddfc3ea2374b02d84b07cf so that elements with a `live` status are always considered refreshable.

You can test this by running `composer require "putyourlightson/craft-blitz:dev-develop as 4.6.1"`.

**Comment by bencroker** [comment]
Released in [4.7.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.7.0).
