### ISSUE TITLE
How to disable locally + What happened to Brotli

### ISSUE THREAD

**Issue by Abromeit** [putyourlightson/craft-blitz#599]
First of all thanks for the awesome work. This is one of the fastest caching solutions I have come across, no matter the CMS. Truly impressive.
<br>

**Q1) Local config**

One question that came up in my team is how to disable the plugin on local dev environments. Unfortunately, we have not found anything about this in the documentation and there does not seem to be a suitable Env variable in the code either.  

I have not had a chance to check this in detail so far, but I can imagine that the problem reports from my developers are legitimate: Even if the .htaccess rules are not active locally, there are probably some elements that are still subject to caching. Which is of course a hindrance if you always need the latest result.

(Additional context: Admin changes are deactivated on our live environment.)
<br>

**Q2) Brotli compression**

We have noticed that the plugin no longer creates br files. This is also documented in your changelog. 

Surprisingly, Brotli actually makes a difference in our current project. (Reduction of the payload per document by approx. 50% compared to gzip. One of the reasons why this gain can be measured is probably that most of our HTML documents in br format are well within the ~14.6kb limit available for the first TCP packet. Whereas this is not the case with GZip. Also we have relatively large documents in this case with inline SVGs etc.)

So this forced us to implement Brotli compression ourselves. This works for us and is perfectly fine. But we are still curious as to why you decided to remove the feature?

**Comment by bencroker** [comment]
Thanks for the kind words, @Abromeit.

1. Disabling the plugin can be achieved using Craft’s [`disabledPlugins`](https://craftcms.com/docs/4.x/config/general.html#disabledplugins) general config setting, however, that will break templates that contain any `craft.blitz.*` tags. Instead, I recommend you disable caching by setting the `cachingEnabled` [config setting](https://github.com/putyourlightson/craft-blitz/blob/0b0f68dad27e96cb63c75c1ecae69e4211bda703/src/config.php#L29) to `false` in development environments.

2. Brotli compression was removed in Blitz [4.5.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.5.0). This was done in order to enable the ability to compress cached values across all cache mechanisms (not just the file cache storage). As part of that, using a single form of compression made much more sense. We opted for gzip, which has more support across web servers and browsers. While Brotli compressed files can be smaller than gzip compressed files, the differences tend to be minimal. I’m willing to reconsider this decision but there would need to be good reason to. If you can provide some benchmarking then that would be very interesting, but saving a few KB alone probably wouldn’t justify it.

**Comment by Abromeit** [comment]
Thanks for the feedback, that makes a lot of things clearer for us now.

The solution for **1)** works for us, great!

On **2)** Nah – I get it. Your argument is completely valid. It's important to have a clean code base that's easy to develop with, without many surprises or exceptions. The next person might come up with Zstd instead of Brotli. Just b.c. we've now browser support for that too. And the reason for requirements shouldn't be _"because browsers can do it"_, but _"what is the effective value for the average project out there"_.  And that is indeed hard to put into objective numbers. 
Even if I can produce a decision basis for a single project that is sufficient for me to implement Brotli myself - that doesn't mean that the data is good enough to cause you additional work.  So – we're cool with that ✌️
