### ISSUE TITLE
Query string with URL encoded characters 404

### ISSUE THREAD

**Issue by eeeeeeeeeve** [putyourlightson/craft-blitz#610]
Craft: Craft Pro 4.5.13
Blitz: 4.9.4
Blitz Query String Caching: 1 (Cache URLs with query strings as unique pages)
Webserver: Apache 2.4.58
Using server rewrites in .htaccess file, as per documentation.

We were previously on Craft 3 using Blitz without a problem, but after migrating to Craft 4, URL encoded query strings no longer seem to be fetched correctly. 

Accessing a URL with query string of `application%5B0%5D=Floor` **OR** `application[0]=Floor` both result in only 1 cache folder generated, the URL encoded version, i.e. `application%5B0%5D=Floor`. But when accessing the URL with an encoded query string `application%5B0%5D=Floor`, it is not able to find a cache file and results in a 404. Accessing the URL with `application[0]=Floor` is successful, and finds the cached file. 

My understanding is that with [this fix](https://github.com/putyourlightson/craft-blitz/commit/7be9930bd912f1489b16813cf8d4579605823d51), it should be generating 2 folders, one encoded, and one decoded.

**Comment by bencroker** [comment]
You're right that URL decoded URIs are normally saved alongside URL encoded folders, however, there are a few characters, including square brackets, that are always encoded.  If the URL encoded version is returning a 404 then this must be considered invalid by either the web server or Craft, so that's where I'd suggest you start looking.
