### ISSUE TITLE
Local generator may not work if `bootstrap.php` is customized

### ISSUE THREAD

**Issue by ccchapman** [putyourlightson/craft-blitz#634]
### Bug Report

**Summary:** The local generator may not work if `bootstrap.php` is customized. The queue job finishes without errors but no pages are warmed. This is presumably because the local generator [does not load](https://github.com/putyourlightson/craft-blitz/blob/3a394ac7da71c43d41412a37837c701677f36b25/src/drivers/generators/local-generator-script.php#L53-L81) your `bootstrap.php` file.

**Steps to reproduce:**

1. `mkdir src/`
2. `mv templates/ src/`
3. `echo 'define("CRAFT_TEMPLATES_PATH", CRAFT_BASE_PATH . "/src/templates");' >> bootstrap.php`
4. Set Blitz to local generator and generate cache

### Plugin Version

4.7.0

### Craft CMS Version

4.5.5

**Comment by bencroker** [comment]
Thanks for the report. I’ve made it so that the bootstrap file is loaded, if it exists, in https://github.com/putyourlightson/craft-blitz/commit/86712ce6dd01d82fad5876b724f41d67cc27c466.

You can test this by running `composer require "putyourlightson/craft-blitz:dev-feature/bootstrap-from-file as 4.13.2"`.
