### ISSUE TITLE
Refreshing Blitz Cache Failing when saving entry

### ISSUE THREAD

**Issue by jmcgaha** [putyourlightson/craft-blitz#65]
Every time I save an entry it runs a task to Refresh Biltz Cache but it fails instantly every time.

If I look at the Queue table in the db it gives an error of: `Invalid argument supplied for foreach()`

If I run the tasks manually or from the console they seem to work fine, its just when saving an entry that it fails.

Using Blitz 1.11.4 and Craft 3.0.37.

**Comment by putyourlightson** [comment]
Thanks for reporting this. Ironically, Blitz 1.11.4 fixed this exact error (or at least one instance of it). Was this an issue before you updated to version 1.11.4 or did it just start hapenning? If you are able to test this with `devMode` on then can you check the `queue.log` file to find the exact error message? Otherwise you can send the log file to info@putyourlightson.net and we'll take a look.

**Comment by jmcgaha** [comment]
I am a dummy.
I just installed it for the first time this morning and assumed it was the latest, but somehow it was actually 1.11.3.
Getting on 1.11.4 fixed it. Sorry about that.

**Comment by putyourlightson** [comment]
Glad to hear you got it working!
