### ISSUE TITLE
Error on save SeoMatic settings

### ISSUE THREAD

**Issue by umkasanki** [putyourlightson/craft-blitz#656]
### Bug Report

We have a large site with Blitz + Cloudflare caching.
The error occurs when we have a lot of cached pages.
While saving the SeoMatic settings, the process of clearing the Blitz cache begins. But since there are many pages, an Timeout error occurs.

Could you configure the execution of cache clearing tasks using jobs?
Thanks

### Plugin Version

4.15.0

### Craft CMS Version

4.8.6

### PHP Version

8.3.6

**Comment by bencroker** [comment]
Are you running the queue via a daemonised queue runner? See more details in this common issue: https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-job-is-stalling

**Comment by umkasanki** [comment]
Yes. We run all jobs through daemons. This works well for other processes.
But when saving the SeoMatic settings, the queue tasks for some reason do not appear. The cache clearing process starts on the fly, without any tasks.
Could you please check this?

**Comment by bencroker** [comment]
> But when saving the SeoMatic settings, the queue tasks for some reason do not appear. The cache clearing process starts on the fly, without any tasks.

How are you seeing the cache clearing process take place?

**Comment by Romanavr** [comment]
Hey @bencroker 

I'm having the same problem, and after some debugging I suggested that the problem might be with the cache update service:

Firstly, here you run the SEOmatic integration https://github.com/putyourlightson/craft-blitz/blob/51ca8e106851da34512087ffa9ac049a7f9c1944/src/drivers/integrations/SeomaticIntegration.php#L38

And then you clear/flush/purge all caches
https://github.com/putyourlightson/craft-blitz/blob/51ca8e106851da34512087ffa9ac049a7f9c1944/src/services/RefreshCacheService.php#L419
I don't see any logic here to push the jobs to the queue, so, in my opinion, the cache clearing happens on the _save_ request 

At first I thought the problem might be in the collecting site URLs for later cache generation, but my refresh mode is `Clean cache, regenerate manually or organically`, so this shouldn't be the case.

Also, the timeout only happens when, for example, **I haven't cleared the cache for a long time,** so when I save the SEOmatic settings for the 1st time, timeout happens, however the next save goes fine because we don't have that many cache records.

The problem is relevant for the "Site Settings" section in the SEOmatic settings, at least for `site.com/admin/seomatic/site/identity/default`

**Comment by bencroker** [comment]
You’re right that with the refresh mode set to `Clean cache, regenerate manually or organically`, the entire cache is cleared, flushed and purged, whenever SEOmatic settings are saved. The cache clear and flush both happen synchronously, while the purge happens in a queue job. They should not be causing timeouts though, since they are not heavy tasks (unless the site is really huge).

Blitz 4.16.4 and 5.1.5 improved the flush process to help avoid database memory issues, so it may be worth updating to the latest version and retesting. If the issue persists, can you please provide the config settings used as well as the Blitz section of project config (removing license keys and secrets) and I’ll take a closer look. Also a screenshot of the main Blitz Diagnostics page would be useful to see.

**Comment by Romanavr** [comment]
> You’re right that with the refresh mode set to `Clean cache, regenerate manually or organically`, the entire cache is cleared, flushed and purged, whenever SEOmatic settings are saved. The cache clear and flush both happen synchronously, while the purge happens in a queue job. They should not be causing timeouts though, since they are not heavy tasks (unless the site is really huge).
> 
> Blitz 4.16.4 and 5.1.5 improved the flush process to help avoid database memory issues, so it may be worth updating to the latest version and retesting. If the issue persists, can you please provide the config settings used as well as the Blitz section of project config (removing license keys and secrets) and I’ll take a closer look. Also a screenshot of the main Blitz Diagnostics page would be useful to see.

Thanks, I'll let you know if updating to the latest version solves the problem.

**Comment by bencroker** [comment]
Great! If the issue persists then please provide a diagnostics report that can be generated in the Blitz Diagnostics utility in version [4.17.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.17.0) and [5.2.0](https://github.com/putyourlightson/craft-blitz/releases/tag/5.2.0) above.

![screenshot-3bsQ075e@2x](https://github.com/putyourlightson/craft-blitz/assets/57572400/87e0ebcf-bf4f-4188-a1b6-3ade696385e1)

**Comment by Romanavr** [comment]
> Great! If the issue persists then please provide a diagnostics report that can be generated in the Blitz Diagnostics utility in version [4.17.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.17.0) and [5.2.0](https://github.com/putyourlightson/craft-blitz/releases/tag/5.2.0) above.
> 
> ![screenshot-3bsQ075e@2x](https://private-user-images.githubusercontent.com/57572400/326218797-87e0ebcf-bf4f-4188-a1b6-3ade696385e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MTk2NjMsIm5iZiI6MTcxNDQxOTM2MywicGF0aCI6Ii81NzU3MjQwMC8zMjYyMTg3OTctODdlMGViY2YtYmY0Zi00MTg4LWExYjYtM2FkZTY5NjM4NWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDE5MzYwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZWRhOThkNTQ0M2VkZjFkODYyY2VlNzdhYmNiYzA5NzBhZGI0YzhmOGUwZmFkOGMyZDM4MmU2ZjE2MjQyYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sXkrEJlkk2ZF-CPBNudObNKf6pKE37vuyZGLMLdnY0A)

Hey @bencroker 
Mostly looks resolved. Saving SEOmatic settings still takes a while when we have a lot of tracked items but no timeout.
Just want to know your opinion, judging by the screenshot, is the number of tracked elements enough to cause such problems, like this issue, or not?
If so, do you recommend anything that will make my site _life_ easier? Except eager-loading, already did it.
![image](https://github.com/putyourlightson/craft-blitz/assets/3519951/bff216d7-da0e-4dda-b838-bda58f2cdaeb)

**Comment by bencroker** [comment]
Can you send the full diagnostics report here or to support@putyourlightson.com so I can take a look?

**Comment by Romanavr** [comment]
> Can you send the full diagnostics report here or to [support@putyourlightson.com](mailto:support@putyourlightson.com) so I can take a look?

Done

**Comment by bencroker** [comment]
Thanks, your configuration looks fine to me. How long is it taking, roughly, to save the SEOmatic settings? This should be the same as refreshing the entire cache via the Blitz cache utility, by the way.

**Comment by Romanavr** [comment]
> Thanks, your configuration looks fine to me. How long is it taking, roughly, to save the SEOmatic settings? This should be the same as refreshing the entire cache via the Blitz cache utility, by the way.

Thanks Ben!
I think everything is good now. Depends on the number of items being tracked/cached: 1-30 seconds, something like that.

**Comment by Romanavr** [comment]
Another question, non-related to this issue.
When I disabled cache (not the plugin, but the caching function itself).
What does "Refreshing Blitz cache" job do?  What does it update/refresh?

**Comment by bencroker** [comment]
> Depends on the number of items being tracked/cached: 1-30 seconds, something like that.

That’s longer than I would expect. I’ll look into whether there are any optimisations that could be made.

> What does "Refreshing Blitz cache" job do? What does it update/refresh?

It clears any cached pages that have become stale, based on the changes just made to an element. If you want to disable that behaviour, you can do so by setting the [`refreshCacheEnabled`](https://github.com/putyourlightson/craft-blitz/blob/aba1fcfccfae3c788d83777800c35dd8a28026b0/src/config.php#L32) config variable to `false`.
