### ISSUE TITLE
Craft asyncCsrfInputs config value

### ISSUE THREAD

**Issue by thijskaspers** [putyourlightson/craft-blitz#706]
### Support Request

Hey Ben,

I was wondering about the new asyncCsrfInputs config setting ([asyncCsrfInputs](https://craftcms.com/docs/5.x/reference/config/general.html#asynccsrfinputs)) and if it will have an impact for statically cached Blitz sites. The Craft changelog mentions:

`Craft now sends no-cache headers for requests that generate/retrieve a CSRF token. If your Craft install is behind a static caching service like Cloudflare, enable the [asyncCsrfInputs](https://craftcms.com/docs/5.x/reference/config/general.html#asynccsrfinputs) config setting to avoid a significant cache hit reduction. ([#15293](https://github.com/craftcms/cms/pull/15293), [#15281](https://github.com/craftcms/cms/pull/15281))` 

Should we use this setting with Blitz or can we stick to solutions like `{{ craft.blitz.csrfToken() }}`?

**Comment by bencroker** [comment]
It is still favourable to use `craft.blitz.csrfInput()` because, as the [docs](https://putyourlightson.com/plugins/blitz#craft-blitz-csrfinput) state:

> This function fetches and injects a CSRF input field in place of the Twig tag via an AJAX request unless called within an AJAX request, in which case the value will be output inline.

This means that the field is fetched using AJAX only when not already in the context of an AJAX request. I don’t think the `asyncCsrfInputs` feature accounts for this, which can trip you up if you aren’t aware of it. 

Does that make sense?

**Comment by thijskaspers** [comment]
It does, thanks!
