### ISSUE TITLE
Blitz CRSF vs. Craft CSRF

### ISSUE THREAD

**Issue by kaspar-allenbach** [putyourlightson/craft-blitz#715]
1. I go to the frontend of my page
2. Then I log in to the CP
3. I go back to the frontend and I add something to the cart which is powered by craft commerce
4. `Error 400 yii\web\BadRequestHttpException: Couldn't verfiy Data submission`

My theory is that a CSRF token is generated on page load, and then another one when logging into the CP, invalidating the old one.

Does blitz have its own CSRF generation separate from craft? I use `{{ craft.blitz.csrfInput() }}` in my templates.

Trying to wrap my head around what happens behind the scenes here.

Craft: 3.9
Blitz: 3.15.0

**Comment by bencroker** [comment]
Blitz creates CSRF tokens using Craft logic, so it does nothing out of the ordinary. 

https://github.com/putyourlightson/craft-blitz/blob/8a71659800f55259b25ec9c8893e6df5db3030ee/src/controllers/CsrfController.php#L34

Looking at the source code, it appears as though [Craft generates a different CSRF token for authenticated and unauthenticated users](https://github.com/craftcms/cms/blob/960cb2f2adb127e586a609d2ad47e25e5d320e38/src/web/Request.php#L1370-L1377), so that is likely the cause of the issue here.

**Comment by kaspar-allenbach** [comment]
thank you 🙏
