### ISSUE TITLE
No blitz hints on a channel page on Craft CMS 5

### ISSUE THREAD

**Issue by philippe-leeroy** [putyourlightson/craft-blitz#727]
### Support Request

There was changes recently in CraftCMS 5 (version 5.4.9)

Before on the `entry` variable into the template, i used :
```
    {% do craft.app.elements.eagerLoadElements(
        className(entry),
        [entry],
        ['myMatrixField',]
    ) %}
```
Because, i had no access to the `entry` query at this point. 

It seems that now, we should use :

`$entry->myMatrixField->eagerly()->collect()`

So I refactored my code, on templates of a single section entries, with `eagerly` and uses blitz hints to find my fields to eagerload.

But, on a template with a channel section, blitz hints reports nothing. But I know that some fields need to be eagerloaded...

So, i'm not sure if CraftCMS 5 now magically eagerload everything or blitz hints is missing something... could you help me with that ?

Another point, the sub fields of a Matrix field does not seems to be report by Blitz Hints... By example, a matrix with an asset seems to be already eager loaded if we rely on Blitz Hint. Is CraftCMS upgraded the eagerloading in a way that matrix sub fields are already eagerloaded ?

### Plugin Version

5.9.1

**Comment by bencroker** [comment]
It has been challenging to keep Blitz Hints working in 100% of cases since the changes introduced in Craft 5. In its current state, the utility should be thought of as an additional tool to collect eager-loading opportunities, rather than a source of truth. I may revisit it in future. If you come across reproducible cases of false negatives (eager-loading opportunities that Blitz should catch but is not), please let me know so I can follow up on them.
