### ISSUE TITLE
Blitz doesn't automatically clear the cache when system status is disabled

### ISSUE THREAD

**Issue by cmalven** [putyourlightson/craft-blitz#83]
Maybe this isn't technically possible, or maybe there's a good reason why it currently behaves this way, but it does seem a bit strange that when I disable system status in Craft settings I have to manually clear the Blitz cache for the unavailable message to display.

**Comment by putyourlightson** [comment]
Could it be that you have server rewrites in place? Those should probably be removed in a development/staging environment or until the site goes live.

**Comment by cmalven** [comment]
@putyourlightson Yes, I do have server rewrites in place. The issue I'm actually referring to is more about when the site _is_ live, and I disable the system in order to put the site into temporary maintenance mode for longer-timeframe updates to be made. Might not be a way around this with server rewrites in place, it sounds like.

**Comment by putyourlightson** [comment]
The way around this would be to clear the cache _before_ putting it into maintenance mode and warm to cache _after_ making it live again.

**Comment by cmalven** [comment]
That makes sense. Just need to find a way to very quickly clear the cache and then immediately go into maintenance mode to avoid the site getting hit in between. Obviously I can clear the caches via the CLI, but not sure there's a way to disable the site via CLI. Anyway, thanks for the assistance. We can call this closed.

**Comment by putyourlightson** [comment]
FYI, I would think it most cases it is beneficial to have the server rewrite serving the cached pages while the CMS is in maintenance mode. That way your visitors can continue using the site while the CMS is being worked on :)

You should still be able to turn on maintenance mode and then clear the Blitz cache, in case that's a better option for you.

**Comment by cmalven** [comment]
That's a very good point!

**Comment by joepagan** [comment]
Hey, just experienced this myself, was totally expecting the 503 template to show.

I appreciate it is desirable for Cloudflare cache not to be purged when system status is offline.

However, sites with heavy API integration where features will be broken during API maintenance is exactly why I think Cloudflare should be cleared. 

Could a config setting please be considered where changing the system status would a particular set of actions run clear, flush & purge?

I think otherwise this is confusing and panic inducing for (non-developer) content editors or CMS admins who may have this responsibility, while they are all aware of caching it is not inherently the first thing they think of.

Update:
Just seen [your comment here](https://github.com/putyourlightson/craft-blitz/issues/356#issuecomment-974628662) ben, great idea my slow brain did not think of, however if I were to access the system status via craft method it would not purge

**Comment by bencroker** [comment]
@joepagan This issue is over 3 years old and refers to an old version of the plugin. Please create a new issue if still applicable to Blitz 4.
