### ISSUE TITLE
Blitz adding an Invisible character resulting in malformed doctype

### ISSUE THREAD

**Issue by jonathanmelville** [putyourlightson/craft-blitz#95]
I noticed that cached pages have a [strange space at the top](https://cl.ly/497374c2bbcb). I looked at a diff of a cached page vs a non-cached page and the even though it looks exactly the same, the diff showed a change in in the opening `<!DOCTYPE html>` declaration. 

I can see by moving my cursor back and forth in my editor that there is indeed an invisible character added before the opening doctype.

Running the cached page through an html5 validator [confirms this](https://cl.ly/dd3113b8b435).

I'm not really doing anything tricky with my setup so I'm not sure how this could be happening.

**Comment by putyourlightson** [comment]
Hi Jonathan, there was a situation that came up recently and has been fixed in the current dev branch. You can check the solution [here](https://github.com/putyourlightson/craft-blitz/issues/89#issuecomment-477730749) and manually apply it if this is a live site, otherwise I'll be releasing the fix in the coming days.

**Comment by jonathanmelville** [comment]
Hey Ben, thanks for the quick response. Commenting out that line does indeed fix the issue.

I'll wait for the next release to deploy, thanks again!

**Comment by putyourlightson** [comment]
Great, it's coming soon!
